### ISSUE TITLE
[TODO] Migrate oemedical base app to version 8.0

### ISSUE THREAD

**Issue by nhomar** [OCA/vertical-medical#1]
Migrate the module and ensure all views open correctly.
This is the simple scope of this point.

**Comment by bmuangkhot** [comment]
Hi Nhomar,

Do you think the porting to ODOO V8 is close soon?

Thanks..

Brice

**Comment by cmoffatt** [comment]
Any status on this?  I am VERY interested in using Medical on Odoo 8.0.

**Comment by bmuangkhot** [comment]
+1

I am interested too for a emerging country..

Thanks.
Brice

2014-11-02 7:05 GMT+07:00 cmoffatt notifications@github.com:

> Any status on this? I am VERY interested in using Medical on Odoo 8.0.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/vertical-medical/issues/1#issuecomment-61388670.

## 

Brice MUANGKHOT

_iTLiGENT_
Le Magellan
7, rue Montespan
91024 EVRY ( FRANCE)
e-mail: bmk@itligent.fr
web: http://www.itligent.fr
Mobile: +33 6 51 59 80 54

**Comment by jvkassi** [comment]
+1
I am very interested too.
This would be very helpful ! Thanks

**Comment by laurenthdl** [comment]
Hi, any hint on this ?
Is help needed to support the 8.0 odoo version ?
Or should this module be considered deprecated ? It would be a shame since it is referenced on the odoo platform.

**Comment by yvaucher** [comment]
I started a PEP8 cleaning here: #6 
Maybe this helps

Perhaps you will want to depreciate them in 7.0 and port them to 8.0

**Comment by fnegrini** [comment]
Interest in contribute. My first contribution will be create an icon for the main module "medical".
Pull request soon.
Icon suggestion for module attached.
![first aid kit-256x256](https://cloud.githubusercontent.com/assets/4683234/8502016/a1449122-2181-11e5-9c1c-b9ada03016a7.png)
![hospital-icon](https://cloud.githubusercontent.com/assets/4683234/8502017/a146e440-2181-11e5-901b-3c322f0c5722.png)

**Comment by lasley** [comment]
Thanks for the icons @fnegrini 

This has been completed aside from the icons. I would say they look better than the ones we have currently, anyone have any additional comments there?

**Comment by lmignon** [comment]
@fnegrini Nice Icons, thank you for the contrib...

**Comment by lasley** [comment]
Looking to integrate these, and I'm thinking that the original core icon https://github.com/OCA/vertical-medical/blob/8.0/medical/static/description/icon.png represents medical as a whole more than the cross emblem. 

I think we should instead use these for the medical_operational module or one of the upcoming splits of the medical_emr module.

**Comment by mikejmets** [comment]
I'm interested in version 8. I'm new to Odoo but I have a prospective client that needs EMR and I can try get him to sponsor my time. Can anyone comment of the effort required to port it from 7 to 8 or backport from 9 to 8 (although 9 still has installable=False)?

**Comment by lasley** [comment]
@mikejmets - v8 is already released and should work well. I cannot comment on backport to v7. My team is currently working on v9, with ~20 PRs pending at this point. I believe our finalization tickets for all those just started coming up, so we should start seeing those move from Work in Progress soon.

**Comment by mikejmets** [comment]
Thanks @lasley, I installed v8 in your fork successfully. It's recommended to me to stay on 8 for clients that insist on zero licence fees. Do you think I should install 9 for my client?

**Comment by lasley** [comment]
All versions are AGPL-3 licensed.

V9 in our fork works well (`release/9.0` branch), but I cannot guarantee production viability/stability quite yet. Most of the modules with PRs up have been solidified in terms of model attributes and all that, but we haven't fully frozen them yet. 

If you're using v8, you can just use the OCA fork. Those are solidified & will be updated more often than our's. My team has moved on from v8, so you won't see any additional work there from our end.

**Comment by yvaucher** [comment]
@mikejmets v9 can still be license fee free as long as you use only the community version instead of enterprise version. Enterprise version is not required for Odoo to work it only adds features. The core of 9.0 is LGPL instead of AGPL.
Nevertheless, there are still more community modules on V8 than on V9, so you might want to stick to V8.

**Comment by lasley** [comment]
v8 core migration has been complete for some time. Closing this.
