### ISSUE TITLE
Odoo Server Error

### ISSUE THREAD

**Issue by IbrahimMAbed** [OCA/vertical-medical#103]
![medical-error](https://cloud.githubusercontent.com/assets/17514986/13373493/fd0d5564-dd71-11e5-8258-cbee391ec13d.png)

**Comment by lasley** [comment]
Hi @IbrahimMAbed - Thanks for the submission. This error is confirmed in v8 & 9. Fixes incoming

**Comment by IbrahimMAbed** [comment]
Another error when i upgrade the module with the new fix but now in the create patient form.
![medical-error1](https://cloud.githubusercontent.com/assets/17514986/13375725/04230cf2-ddb0-11e5-860d-8ad9fa3f28ba.png)

**Comment by IbrahimMAbed** [comment]
Another one :cry: 
![medical-error2](https://cloud.githubusercontent.com/assets/17514986/13375766/f2f479ba-ddb0-11e5-8561-9ae7573fd2f2.png)

**Comment by lasley** [comment]
Hah ok let me actually test this in V8, I just directly backported from the 9 changes. Must be something different in the cores that I forgot about :smile:

**Comment by lasley** [comment]
@IbrahimMAbed Ahh so it was an issue with there being no patient_id on initial creation. We should be good to go now, my bad on the oversight.

**Comment by lasley** [comment]
Closing to track in PR #104 - please provide review or additional comments there
