### ISSUE TITLE
Project Translation

### ISSUE THREAD

**Issue by juhenriquez** [OCA/vertical-medical#114]
Is there any project translation on transifex where one would contribute by translating the term on the modules?

**Comment by hejiann** [comment]
There has no .po files in modules. How to generate the .po file?

**Comment by lasley** [comment]
@pedrobaeza - Can you maybe point me in a direction in order to generate these PO files? I'm clueless on everything translation TBH

**Comment by pedrobaeza** [comment]
I have updated .travis.yml files to include Transifex, so I close.

**Comment by lasley** [comment]
Good to know that's all it takes, thanks @pedrobaeza
