### ISSUE TITLE
Error installing the "Medical EMR" module

### ISSUE THREAD

**Issue by SiriusFuenmayor** [OCA/vertical-medical#115]
Hi, I have managed to install all the modules of vertical-medical except for "Medical EMR", when I try I get the following error: 

```
2016-07-27 14:07:43,200 27738 CRITICAL odoo_db openerp.modules.module: Couldn't load module medical_emr
2016-07-27 14:07:43,200 27738 CRITICAL odoo_db openerp.modules.module: cannot import name medical_pathology_category
> /home/sirius/Projects/vertical-medical/medical_emr/models/__init__.py(23)<module>()
-> from . import medical_pathology_category
```

Any ideas regarding this error?

**Comment by SiriusFuenmayor** [comment]
I'm talking about the 8.0 branch version of the Medical EMR module and Odoo 8

**Comment by lasley** [comment]
Hi @SiriusFuenmayor - Medical EMR is not compatible with v8, and is fully deprecated in 9.

For general rule of thumb - if you have to edit the `__openerp__` file to make something installable, it is not supported on your version.

**Comment by SiriusFuenmayor** [comment]
Thank you Dave, I have also tried to install oemedical in Odoo 8 but the installation takes forever, I have seen here [](https://github.com/OCA/vertical-medical/issues/1) that you are trying to port oemedical to version 8, what is the current status of this?

**Comment by SiriusFuenmayor** [comment]
Thank you Dave, I have also tried to install oemedical in Odoo 8 but the installation takes forever, I have seen here (https://github.com/OCA/vertical-medical/issues/1) that you are trying to port oemedical to version 8, what is the current status of this?

**Comment by lasley** [comment]
Anything with an `oe` prefix is deprecated and will be replaced with a non-`oe` module with the same name.

In this case, `medical` was the replacement. `emr` is in the process of being split into the modules you see here w/ non-oe prefixes + what is left in the folder (also why it is unusable).

TBH - my team is working on v9, so there will be no further forward development in regard to v8 from my end. Our current v9 version is at https://github.com/laslabs/vertical-medical/tree/release/9.0 & is pretty damned nice IMO

**Comment by SiriusFuenmayor** [comment]
Thank you again, I will look into that

**Comment by lasley** [comment]
Closing - this is an unported module as mentioned in previous comment
