### ISSUE TITLE
[RFC][11.0] Medical Menu Redesign

### ISSUE THREAD

**Issue by lasley** [OCA/vertical-medical#127]
I am working on a redesign for the layout of medical menus for v10. Currently everything is under a central `Medical` app with a series of submenus, most of which are under `Configuration` (screenshot at bottom of this message). The current layout is unwieldy in terms of usage for Community web, and looks like absolute garbage on Enterprise or `web_responsive`. 

Current plan is as follows:

* Dashboard (TBD what this actually is)
* Inventory
  * Medicaments
  * Insurance Plans
* Patient
  * Patients
  * Diseases
  * Medications
* Scheduling
  * Appointments

----

**Leftovers that need to be placed:**

* Prescription
  * Prescription Orders
  * Prescription Order Lines
* Configuration
  * Disease
  * Pathologies
  * Pathology Categories
  * Pathology Groups
* Health Professionals
  * Physician [Self]
  * Physician [Assistant]
* Medicaments
  * Medicaments
  * Attribute Types
  * Attributes
  * Storage Instructions
  * Medication Template
  * Medical Manufacturers
  * Drug Admin Route
  * Drug Form
  * Medication Dosage
* Misc
  * Medical Specialty
  * Insurance
    * Insurance Providers
    * Insurance Plans
    * Insurance Plan Templates
  * Pharmacies

----

**Current Menus:**

![image](https://cloud.githubusercontent.com/assets/7397578/20335495/f3216638-ab77-11e6-9ee2-37c352810ed7.png)

**Comment by pedrobaeza** [comment]
With new app centric top menu, I think you should split them into several top menus with a proper icon.

**Comment by lasley** [comment]
I think you've got a good point @pedrobaeza. It might also make sense to make different "Apps" for different contexts, instead of just adding into menus in all of the independent packages. 

At this point the vertical-medical repo is fairly granular, so it may make sense for some sort of super-package hierarchy. Say you're running a pharmacy, you install `medical_app_pharmacy` which would install:
* medical
* medical_pharmacy
* medical_physician
* medical_medicament
* and the 10 or so other dependencies required for selling medications

It would then provide a context-specific app in the App Drawer for Pharmacy use, containing the items they need in the layout they need it. Maybe even some permissions/ACL hierarchy, which is something we're missing right now.

Similar apps could be provided for Doctor, Hospital, Lab, etc.

**Comment by lasley** [comment]
I'm moving this to 11.0 milestone for the `medical` app. We may just kill this menu entirely in favor of an approach taken in https://github.com/laslabs/vertical-medical/pull/44, which is the `medical_app_*` concept that is somewhat laid out in https://github.com/OCA/vertical-medical/issues/127#issuecomment-262062827

Admittedly I want to get rid of the `medical` module altogether, so this would align with that goal.

**Comment by lasley** [comment]
The overall redesign of all menus is completed in LasLabs#84. Additional menus will be created via new applications for specific medical contexts, such as medical_app_pharmacy in LasLabs#44.

I am closing this to track in PR
