### ISSUE TITLE
Odoo Apps Store Charging for Vertical-Medical

### ISSUE THREAD

**Issue by lasley** [OCA/vertical-medical#133]
The following apps have mysterious 500 EU price tags:
* https://apps.odoo.com/apps/modules/9.0/medical_patient_disease_allergy/
* https://apps.odoo.com/apps/modules/9.0/medical_patient_disease/

Sent email to Odoo Apps support. Pretty sure it's due to an incorrect module being linked in the dependencies:
* https://apps.odoo.com/apps/modules/9.0/medical_pathology/

**Comment by lasley** [comment]
Received a response from Odoo SA, who advised that the module name was taken (as noted in my original comments).

I took a look at the conflicting module by Pragmatic, and it was obviously based from `oe_medical_lab`. Opened licensing dispute, Odoo SA confirmed this module was plagiarized, and removed from Apps Store.

**Comment by lasley** [comment]
cc @OCA/board 

FYI Pragmatic [has verticals that all look nearly identical to OCA's](http://www.pragtech.co.in/products.html). With the fact that they plagiarized vertical-medical, I find it likely these are suspect as well. I'm not sure the handling of this though, because I only know medical well enough to cry wolf accurately.

**Comment by dreispt** [comment]
At this moment, the best we can do is what you did - report it to Odoo.

We could put on the OCA Board agenda discussing with Odoo about the apps plagium issues.
It is also Odoo's interest to solve this, since customers buying plagiarised modules from the App store are at a legal risk (from being sued by the original authors, and maybe even forced to AGPL their private custom code).
Something like a bot comparing key metrics in modules could be a solution. But it needs access to sources and only the App store owner can do that.

**Comment by lasley** [comment]
Yeah that's pretty much the situation as I understand it too @dreispt. I got lucky in the sense that there was a spelling error smack dab in the middle of everything, so it was spottable in their marketing videos. Really I would have never looked had there not been a namespace conflict though.

An interesting conundrum created by this is that the new module replacing the plagiarized one ( #137 ) is entirely incompatible with their version & is going to cause some massively broken databases for the 20 some odd people that actually bought the app.

In this situation, they had changed all the key metrics so a simple monitor like that wouldn't have worked. It would need to be actual code scanning, but the note you made about needing access to the code nullifies that entirely. Too bad Odoo doesn't offer proactive content protection, like Youtube.
