### ISSUE TITLE
[9.0] Module renames added to OpenUpgrade

### ISSUE THREAD

**Issue by lasley** [OCA/vertical-medical#160]
Many modules were renamed between 8 and 9. The changes are all documented in the ReadMes for the most part, but we need to add to OpenUpgrade - https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/addons/openupgrade_records/lib/apriori.py

One thing I'm not sure about is what to do when a module was split into separate modules. This has happened quite a bit.

**Comment by pedrobaeza** [comment]
If a module has been split, the strategy can be to rename the old one to one of them, and include a migration script in it that mark the state of the other module as "to install". Example: https://github.com/OCA/OpenUpgrade/blob/338b2be4af22334c3329367274cccb2dd62dee78/addons/product/migrations/9.0.1.2/pre-migration.py#L90

**Comment by lasley** [comment]
Brilliant, thanks for the insight @pedrobaeza. I have admittedly not used OpenUpgrade yet, so I'm operating on purely hypotheticals. Our internal site is going to need upgrading soon though, so that will likely be a repo you will begin to see me in soon 😸
