### ISSUE TITLE
[9.0][BUG] medical_family: Views missing

### ISSUE THREAD

**Issue by lasley** [OCA/vertical-medical#169]
The newly upgraded `medical_family` module is not properly showing all views. 

@kellylougheed - Please audit the views in the module against the views that are actually showing.

**Comment by kellylougheed** [comment]
@lasley The views looked fine to me on release/9.0, although when I tried to create a family for a patient (by going to the patient's profile and then to the "Family" tab), I got this error: `AttributeError: 'medical.patient' object has no attribute 'onchange_state'` Is that what you meant?
