### ISSUE TITLE
No repository/runbot for v8.0 ?

### ISSUE THREAD

**Issue by dek-odoo** [OCA/vertical-medical#208]
Seems like I am missing something.

Edited: I saw repo at [Laslabs](https://github.com/LasLabs/vertical-medical/), but it is not available on this repo.
Thanks

**Comment by lasley** [comment]
v8 code is suspect licensing. Please see https://github.com/OCA/vertical-medical/issues/183#issuecomment-320460831

**Comment by lasley** [comment]
There's also a note in the [most recent newsletter](https://odoo-community.org/blog/our-blog-1/post/oca-fall-newsletter-2017-3-72) for anyone using this code.
