### ISSUE TITLE
[TODO] Module medical became Application

### ISSUE THREAD

**Issue by fnegrini** [OCA/vertical-medical#21]
Activate de Application property in medical module with its own icon.

**Comment by fnegrini** [comment]
The icon for the App should be in [medical]\static\description
I have a pull request ready to upload but I don't have permission.
Could anyone allow me to do so?

**Comment by yvaucher** [comment]
@fnegrini Anyone can make a Pull request just fork the repo, and push to you fork then from your uploaded branch create the pull request on the trunk

**Comment by fnegrini** [comment]
@yvaucher I think I did it wong. I'll try to do according to these steps. The pull request will be done by tomorow.
Thanks!

**Comment by fnegrini** [comment]
Pull request #28 created for this issue.

Thanks!

**Comment by fnegrini** [comment]
Followed the steps. Please check pull request #29.

**Comment by fnegrini** [comment]
Pull #30. Now I also removed the old folder.

**Comment by fnegrini** [comment]
Closing issue!
