### ISSUE TITLE
11.0-dev ready to review!

### ISSUE THREAD

**Issue by rgarnau** [OCA/vertical-medical#210]
We have been implementing the new Odoo Medical v11 strictly following the FHIR standard and we think it is ready for the first review! Therefore, we have push the whole project into a new branch 11.0-dev in the OCA/vertical-medical repo (https://github.com/OCA/vertical-medical/tree/11.0-dev) so you can test the overall workflow!

As explained, the project follows the FHIR structure which divides the implementation into 7 basic categories:
* Administration
* Clinical
* Workflow
* Financial
* Diagnostics
* Medication
* Terminologies

Each of these categories initializes (normally as abstract classes) all the modules belonging to each of these categories, in order to make the approach of extending the Odoo Medical more flexible.

Once the general workflow is tested, we propose to jump into 11.0 branch and start making PR for each of the modules to carefully review them.

**Comment by lasley** [comment]
@rgarnau I'll take a look this week.

I think we have an issue though - Transifex commits are coming through on the [11.0 branch](https://github.com/OCA/vertical-medical/tree/11.0/medical_administration/i18n). Please take a look.

**Comment by rgarnau** [comment]
@lasley we have disabled Transifex for now and the 11.0 branch is clean again.

**Comment by rgarnau** [comment]
11.0-dev branch has been removed, so this issue is no longer valid.
