### ISSUE TITLE
8.0 was deleted, I badly need that branch

### ISSUE THREAD

**Issue by IJOL** [OCA/vertical-medical#226]

**Comment by pedrobaeza** [comment]
It was removed due to a license infringement claim, so you can consider in danger using it, but if you still want to use it, copy it from other place you have.

**Comment by IJOL** [comment]
OK, thank for the quick response, yep we will need to recover where is working now, not sure if used at all, but needed in the deploy procedure,

Saludos,
Ignacio J. Ortega
