### ISSUE TITLE
All module are not imported in odoo10

### ISSUE THREAD

**Issue by susankc** [OCA/vertical-medical#227]
As now this module is version 10 and i have install all the module but all the requirement is not captured and version 8 is also not available, are you guys are working on update or any update ? let us know  we really need all complete system so can anybody can help ?

**Comment by susankc** [comment]
Anybody to reply anything about this ? @pedrobaeza anybody ?

**Comment by etobella** [comment]
vertical-medical had some issues due a licensing dispute #183.
As far as I know, nobody is maintaining it.
