### ISSUE TITLE
DoB calendar bug

### ISSUE THREAD

**Issue by nuria-opusvl** [OCA/vertical-medical#25]
64 bit Debian Wheezy 7.8
Odoo 8.0.20150515
in lxc container
using Firefox 39.0

Hi,

I installed the medical base module for testing and noticed a small bug on the DoB calendar when creating a new patient.

When you click on the year drop down, you only have a selection of years from 2005, and it shows lots of future years.

I clicked on the earliest it allowed me (2005) and saved it.

Then I edited again the patient and clicked on the DoB year selection, and earlier years came up.

I clicked on the  earliest year, which this time was 1995, but when I pressed "Done" it didn't change and it didn't save it.

I thought you would like to know.

All the best,
Nuria

**Comment by lasley** [comment]
Hi @nuria-opusvl - I believe we have fixed this in branch `8.0-incubator`. Please give it a shot on your side and let us know - Thanks!

**Comment by nuria-opusvl** [comment]
Thanks for the heads up!

:-)

On 05/10/15 09:54, Dave Lasley wrote:

> Hi @nuria-opusvl https://github.com/nuria-opusvl - I believe we have 
> fixed this in branch |8.0-incubator|. Please give it a shot on your 
> side and let us know - Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/vertical-medical/issues/25#issuecomment-145466842.

## 

N. Arranz-Velazquez
OpusVL Odoo Specialist Team (OOST)
Product Owner

OpusVL
Drury House
Drury Lane
Rugby
CV21 3DE

T: 01788 298 450
W: www.opusvl.com

**Comment by lasley** [comment]
This should be resolved with the current version (8). Please let us know, or close the ticket if resolved. V9 is in the works, and includes the same fix.
