### ISSUE TITLE
Can't find medical module in addons in Odoo

### ISSUE THREAD

**Issue by ekitsikpui5** [OCA/vertical-medical#35]
I have an issue seeing medical module in Odoo, I have done all what is required and checked this error in other databases as well as platforms.

**Comment by ghost** [comment]
When you add the medical Oemedical module in the addons folder on your server you must create a new database

**Comment by lasley** [comment]
What version of Odoo and what Git branch? Have you updated the modules list through the admin panel?

**Comment by lasley** [comment]
This should be resolved with the current version (8). Please let us know, or close the ticket if resolved.
