### ISSUE TITLE
Istallation Error with Oemedical v7 on odoo v7

### ISSUE THREAD

**Issue by ghost** [OCA/vertical-medical#37]
Hello
last time i had try to install Oemedical oca/vertical-medical on Odoo v7 and i got this Error: ValidateError Error occurred while validating the field(s) arch: Invalid XML for View Architecture!

Someone can help pls???????????

**Comment by yvaucher** [comment]
@sandaly Developpement focus is on 8.0 version. 7.0 was not ported and has many conflicts in views.

You can see the progress here on github in the issues and Pull requests

https://github.com/OCA/vertical-medical/pulls

The most advanced base branch is https://github.com/OCA/vertical-medical/tree/8.0-incubator
and pull requests are targeting it.

**Comment by lasley** [comment]
Current development plans do not include Odoo versions before v8. I recommend upgrading, then using the current v8 (or soon v9) branch.

**Comment by lasley** [comment]
Closing ticket, v7 is unsupported
