### ISSUE TITLE
error when I tried to install the Gynecology module

### ISSUE THREAD

**Issue by casisa** [OCA/vertical-medical#4]
any hint how to solve this?

ValueError: No such external ID currently defined in the system: oemedical_gynecology_and_obstetrics.act_open_oemedical_patient_view

**Comment by yvaucher** [comment]
@casisa `oemedical_gynecology_and_obstetrics.act_open_oemedical_patient_view` is not found in XML files of installed module.

It can be a missing dependency, a typo in view name or `act_open_oemedical_patient_view` is in another module.

Please also specify the version of Odoo you are using.

**Comment by yvaucher** [comment]
It seems the error comes from:

https://github.com/OCA/vertical-medical/blob/7.0/oemedical_gynecology_and_obstetrics/views/oemedical_menu.xml

Adding `oemedical.` before all ids should solve it. Thought it seems strange to have duplicated menu items of those from https://github.com/OCA/vertical-medical/blob/7.0/oemedical/views/oemedical_menu.xml

**Comment by casisa** [comment]
i tried to install the module using OpenERP 7 or Odoo 8, but on both I had errors. I installed oemedical module first, and it works fine. I downloaded oemedical modules from the github repository and from the odoo repository, but I got errors with both. So does it happen that these are not the right files?

**Comment by yvaucher** [comment]
@casisa I'm not the maintainer of this project. I had a look at `oemedical_gynecology_and_obstetrics` and menu definition are not usable at all and needs an huge cleaning. So it is not installable neither on 7.0 and 8.0.

**Comment by yvaucher** [comment]
@nhomar anything you planned to do for it here?
BTW I offered you a little pep8 cleaning here: #6

**Comment by TheCloneMaster** [comment]
Hi,

We will be doing some clean up and enabling a couple more modules in the following days, including EMR and invocing from appointment...

**Comment by jacksolutions** [comment]
any update on the more modules of v8?

**Comment by lmignon** [comment]
@TheCloneMaster PLZ take a look at #22 to avoid overlaps in what they are doing and what you do. This PR fix a lot of issues, clean up the code to follow the coding guidelines, etc...

**Comment by lasley** [comment]
Hi all - I am closing this, as it is related to a v7 module that is not being carried forward into newer versions anytime soon. 

We will gladly review PRs to clean the module up & upgrade.
