### ISSUE TITLE
medical_medication Discussion

### ISSUE THREAD

**Issue by lasley** [OCA/vertical-medical#42]
Not really sure of a better way to start this discussion, so please let me know if there is one. Wiki seemed a bit hard to manage in terms of understanding opinions. This is a blocker in our current project, so I'll be tackling it next.

I noticed @JonathanNEMRY's change notes in the wiki for the EMR module, and I fully agree about the modularity. Maybe we should start by breaking the two functional improvement suggestions into their own module (medications, templates, dosages, medicaments + categories => medical_medication or similar)

I'm going to copy/paste the wiki entry then provide my thoughts as a comment just to keep the two separate. 

---
##### Medication And Medication Template

Major issue is that the start-end date is defined on medication and not on medication template.
So this forces to create as much template as patient

Data model should be review with inclusion of an abstract concept. (to discuss)
##### Medicament:

Current implemented version introduce a ambigous relation between 'medical.medicament' and 'product.product' which may possibly beeing a source of additional complexity into the invoicing process of Odoo as product is the core of its billing process
This notion has to be reviewed with two possible solution
- remove medical.medicament and add complementary fields into product.product just as membership (is_membership) or expend (can_be_expend)
  (side effects: product table become too big and user see useless things (more complex views management))
  or
- use a real inherits to 'product.product' and keep additionals fields introduced by medical.medicament (possible problems: there already is a inherits from product.product to product.template)

**Comment by lasley** [comment]
My thoughts

##### Medication And Medication Template

Definitely agree that the start and end should not be in the medication & templates. Shouldn't we maybe just pull that out altogether and let the `medication.order` dictate that (below)? 

In order to cover over-the-counter items, I propose that we create `medication.order` - then inherit `prescription.order` from that to cover all the doctor related stuff. Dates and times are related to an order, not the product or template, so should be treated as such IMHO

I also think that `prescription.order` and associated should just be included in the pharmacy module we're creating, but that's another discussion :wink: 

##### Medicament:

I'm wondering if we need another dimension here. @JonathanNEMRY brought up a good point with the tables getting large, which is only going to compound with the pharmacy module that we are in the process of creating.

The issue is that there are multiple medicament dispense types, dosages, routes, etc. for the same "item". We can already see this becoming an issue when the `medical_emr_data` module starts coming into play (see morphine - All of the different methods of ingestion, UOMs, etc. have all been grouped into the notes section).

I propose something like this:
- `medicament.composition` - Contains the base chemicals making up the medicaments (eg sumatriptin, morphine). This will also contain the adverse reactions, and basically everything else related solely to the drug.
  - We would likely need a Many2many to relate compositions to each other, as they can be composed of multiple items.
  - I asked a friendly pharmacist how the allergies and reactions stack as items are mixed. Was advised that most of the time they are inherited from the compositions, but the act of combining the chemicals can also create allergies and reactions as well. Not sure of the best way to handle this 
- `medicament` - Real inherit from product.product, One2many => medicament.composition.
  - Note - sorry my newbness is missing why product.product => product.template inheritance is an issue. Would someone mind elaborating?

**Comment by JonathanNEMRY** [comment]
Hi @lasley ! I have pushed some Pull Request about Disease/Medicament/Medication/Prescription Order. Don't hesitate to review/comment them. I had no other choice but to make them interrelated because of the module dependencies. I'have also updated the wiki graph.

Jonathan

**Comment by lasley** [comment]
Hi @JonathanNEMRY 

Awesome, thanks for the update! I'll take a look now.

Agreed that there was not a way to create an interdependency between the modules. We're going to run into a bit of that with the EMR stuff, I'm sure that's why it was all originally just dropped into one module.

**Comment by lasley** [comment]
I believe we're covered this conversation, closing
