### ISSUE TITLE
References to oemedical on branch 8.0

### ISSUE THREAD

**Issue by nuria-opusvl** [OCA/vertical-medical#51]
Hi,

Dependencies on **openerp**.py files seem to point out to oemedical instead of medical, which causes install to fail.

I think this has been fixed on branch 9.0 but not on 8.0

Ta,
Nuria

**Comment by lasley** [comment]
Hi @nuria-opusvl

Currently the only module available in 8.0 branch is the core `medical`. All other modules are under heavy development in 8.0-incubator branch & associated pull requests - https://github.com/OCA/vertical-medical/tree/8.0-incubator & https://github.com/OCA/vertical-medical/pulls

**Comment by nuria-opusvl** [comment]
Thanks Dave.
