### ISSUE TITLE
'Installable', False

### ISSUE THREAD

**Issue by nuria-opusvl** [OCA/vertical-medical#52]
Hi again,

I've also found that most ported modules on branch 8.0 have the installable parameter set to false in the **openerp**.py.

Thanks,
Nuria

**Comment by yvaucher** [comment]
Hello @nuria-opusvl 

Modules which are set as uninstallable are modules of previous version which needs adaptation to work properly in 8.0. For current status on 8.0 you can follow the work in progress in the branch `8.0-incubator`

https://github.com/OCA/vertical-medical/tree/8.0-incubator

Cheers,

**Comment by nuria-opusvl** [comment]
Thanks Yannick,

but I must be missing something because I thought of cloning the 
incubator branch and found only one of the modules available, 
oemedical_his. The rest are not in the ported list.

Ta,
Nuria

On 19/10/15 15:18, Yannick Vaucher wrote:

> Hello @nuria-opusvl https://github.com/nuria-opusvl
> 
> Modules which are set as uninstallable are modules of previous version 
> which needs adaptation to work properly. For 8.0 you can follow the 
> work in progress in the branch |8.0-incubator|
> 
> https://github.com/OCA/vertical-medical/tree/8.0-incubator
> 
> Cheers,
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/vertical-medical/issues/52#issuecomment-149226238.

## 

N. Arranz-Velazquez
OpusVL Odoo Specialist Team (OOST)
Product Owner

OpusVL
Drury House
Drury Lane
Rugby
CV21 3DE

T: 01788 298 450
W: www.opusvl.com

**Comment by yvaucher** [comment]
@nuria-opusvl The rest is in Pull requests targeting branch `8.0-incubator` in review or dev process

https://github.com/OCA/vertical-medical/pulls

**Comment by nuria-opusvl** [comment]
Ok, thank you.
