### ISSUE TITLE
Appointment in the same time

### ISSUE THREAD

**Issue by mmendozadelsolar** [OCA/vertical-medical#56]
in runbot: 8.0-incubator

It don't have a timetable of physician to do the appointment. You can make an appointment with the same physician at the same time:

![appointment odoo](https://cloud.githubusercontent.com/assets/7729857/11228606/ccee4f98-8d5b-11e5-8455-4bdb4d7c397b.png)

**Comment by lasley** [comment]
Thanks for the report! Issue confirmed to also be present in current dev head, no appointment time validation currently exists.

This should likely be added to the confirm method, so that draft entries don't create conflicts. This isn't a side of vertical-medical that I've needed, so I'm not really sure how this should operate in a real workflow.

**Comment by mmendozadelsolar** [comment]
I think it can work this way:

1.-Select patient
2.-Select physician
3.-Odoo charge the list of the avaible appointmnet for the physician.

This way the appoitment wont mix. We can add a constraint in the "Appointment ID".

Under this prespective, we will need a button in the physician form to generate the appointments. To do this, maybe we can use the list view of the calendar app and the option of recurring appointment.

The user can generate the appointment of the physician 1 a month or when ever is necesary.

**Comment by lasley** [comment]
Now that we're talking wizard and logic, this is likely another candidate for something that should be a module instead of being included in the main library. @JonathanNEMRY or @lmignon - thoughts?

**Comment by lasley** [comment]
This somewhat exists in `medical/wizard/medical_physician_unavailable_view.xml` now that I'm looking at it. Seems like the blocking of the schedule is explicit vs. implicit by their schedule.

**Comment by lasley** [comment]
@mmendozadelsolar - This should be resolved with the current version. Please let us know, or close the ticket if resolved.

**Comment by pedrobaeza** [comment]
I close also as giving this as solved
