### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by owerfelli** [OCA/vertical-medical#62]
hi everybody
when I try to execute $git clone git@github.com:oca/vertical-medical.git
I have the next error :
.....
Cloning into 'vertical-medical'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
..
thank you for the help

**Comment by lasley** [comment]
Hi @oussamaw - You need to use the HTTPS clone URI unless you have write access to the repo. Also, I recommend using the `8.0-incubator` branch. Try:

```
git clone https://github.com/OCA/vertical-medical.git -b 8.0-incubator
```

**Comment by owerfelli** [comment]
thank you @lasley 
I'm done it but whit 9.0
but i have another error when I execute the push command and I make my user name and password  :
...
fatal: unable to access 'https://github.com/oca/vertical-medical.git/': The requested URL returned error: 403

**Comment by lasley** [comment]
Hi @oussamaw - You wouldn't want to push unless you're making changes. If that's the case, you'll want to fork the repo, use your own checkout for development, then submit a pull request. Take a look at https://github.com/OCA/maintainer-tools/wiki for more info

**Comment by lasley** [comment]
Also FYI - this repo is under heavy development, and 9.0 is not usable. We are currently developing in the 8.0-incubator branch; all plans to upgrade to 9.0 will proceed once that incubator has been completed.

**Comment by owerfelli** [comment]
thank you @lasley 
so i will change the branch,
and i must use odoo 8 ?

**Comment by lasley** [comment]
That is correct

**Comment by owerfelli** [comment]
thank you, you are too helpful :)

**Comment by lasley** [comment]
No problem, would you mind closing the ticket please?
