### ISSUE TITLE
Tradução - Portugês Brasil

### ISSUE THREAD

**Issue by ghost** [OCA/vertical-medical#63]
Olá, gostaria de saber quais são os arquivos de idioma do modulo, gostaria de traduzir e quem sabe usar. notei que ele não usa o mesmo padrão de idioma que a grande maioria dos módulos odoo.

**Comment by lasley** [comment]
Olá - obrigado para a apresentação. Estamos actualmente a falta de arquivos de tradução, mas eu não sei exatamente como gerá-los

Nós temos uma outra questão que veio depois de um presente, mas é em Inglês, por isso estou indo para fechar esta para rastrear sob essa - #114
