### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by chong-richard** [OCA/vertical-medical#67]
Hi,

I have install the Odoo Medical Module in my Odoo Version 8 running on Ubuntu Instance.

I try to install all other module but was being prompt about the following attached. 
<img width="905" alt="odoo medical error" src="https://cloud.githubusercontent.com/assets/16298578/12440138/67ab5ca8-bf73-11e5-948a-a7fc1ed7affa.png">
<img width="453" alt="odoo medical error2" src="https://cloud.githubusercontent.com/assets/16298578/12440139/67b76e3a-bf73-11e5-8de3-b72da1fe0940.png">

**Comment by lasley** [comment]
This should be resolved with the current version. Please let us know, or close the ticket if resolved.

**Comment by chong-richard** [comment]
Hi,

Which current version do you mean?

Richard Chong
Mobile : +65 96557994tel:+65%2096557994
Email : richard@kloud-soft.commailto:richard@kloud-soft.com
Sent from Outlookhttps://aka.ms/qtex0l

On Sat, Jan 30, 2016 at 11:32 PM -0800, "Dave Lasley" <notifications@github.com<mailto:notifications@github.com>> wrote:

This should be resolved with the current version. Please let us know, or close the ticket if resolved.

##

**Comment by pedrobaeza** [comment]
I directly close as Travis says us that they install.

@chong-richard, the one we have just pushed.

**Comment by chong-richard** [comment]
@ Pedro,

So i go back to github to find the file and install again right?

Richard Chong
Mobile : +65 96557994tel:+65%2096557994
Email : richard@kloud-soft.commailto:richard@kloud-soft.com
Sent from Outlookhttps://aka.ms/qtex0l

**Comment by pedrobaeza** [comment]
Yeah, download latest 8.0 branch (with git or manually the zip).

**Comment by aiman-leghrib** [comment]
Hi, im trying to install vertical-medical but  after i  instaled successfully the first medical module its appear in my local module so i tried to install medical_disease by adding the directory on the addons path but it doesn't appear in my local module can anyone help me step by step to install the other modules .thanks by the way im using odoo 8 on ubuntu 16.04
