### ISSUE TITLE
OpenERP doesn't find oemedical modules

### ISSUE THREAD

**Issue by kkoci** [OCA/vertical-medical#7]
Hi

I'm trying to install all this suite of modules.

But neither Odoo v8 or Odoo v7 can find ALL of these modules when declared as addons.

The only one I can see and install is main oemedical, am I missing something?

Thanks in advance.

**Comment by yvaucher** [comment]
@kkoci I'm not sure in what version where these module developed, maybe in 6.1.
What I can tell is that they haven't been ported to 8.0. And only main module was ported to 7.0.

In 7.0 almost all of them have `installable` set to `False` in their `__openerp__.py` manifest.

If you want to try to install them, you will need first to set this value to True.

I just warn you that they will probably not work without some correction mainly in the XML views.

**Comment by TheCloneMaster** [comment]
EMR and invoicing will be available for v8 in the following days...

**Comment by kkoci** [comment]
Ok, thank you very much.

@yvaucher I found another repo which works prefectly.

I'll post it as soon as I find it again, lol

Awesome @TheCloneMaster

**Comment by yvaucher** [comment]
@kkoci you might talk about vauxoo. I think they merged few things already in 8.0

**Comment by lasley** [comment]
8.0-Incubator is where most of the 8.0 stuff is at the moment, it's in heavy development and I would not use on a production system.

**Comment by lasley** [comment]
This should be resolved with the current version (8). Please let us know, or close the ticket if resolved. V9 is in the works, and includes the same fix.
