### ISSUE TITLE
http://medical.odoo.com is an empty page

### ISSUE THREAD

**Issue by lepistone** [OCA/vertical-medical#9]

**Comment by yvaucher** [comment]
@lepistone where is this?

**Comment by lepistone** [comment]
@yvaucher in the description of the repository

**Comment by yvaucher** [comment]
Ok let's conjure an OCA wizard with enough power to fix this.

@nhomar @gurneyalex @StefanRijnhart @max3903 @jgrandguillaume @sebastienbeau 

One of you can fix :sparkles: this ?

**Comment by StefanRijnhart** [comment]
Sure. Which URL do you want instead?

**Comment by yvaucher** [comment]
@StefanRijnhart I think we can simply remove it. If we want an url we can put it later in README

**Comment by StefanRijnhart** [comment]
OK, done.

**Comment by yvaucher** [comment]
@StefanRijnhart Thanks
