### ISSUE TITLE
Why make it not installable?

### ISSUE THREAD

**Issue by xiasun** [OCA/vertical-medical#98]
Thank you for this project, I was trying to study this module somehow but i found all modules are flaged "installable = fasle", So why are these modules uninstallable now? 

*_The way I use this project: *_
Paste the total "vertical-medical" folder to my odoo path, then add it to the "addons-path" in the config file. Then modify the "medical/**openerp**.py" and mark installable true. Then restart the server.

Following error message occurs when click the install button from the localhost:app page: 

> File "/home/summersun/Dev/odoo9.0erp/odoo9.0erp/openerp/modules/registry.py", line 84, in **getitem**
>     return self.models[model_name]
> ParseError: "ir.sequence.type" while parsing /home/summersun/Dev/odoo9.0erp/odoo9.0erp/vertical-medical/medical/views/medical_sequence.xml:6, near
> <record id="seq_type_medical_patient" model="ir.sequence.type">
>             <field name="name">Medical Patient</field>
>             <field name="code">medical.patient</field>
>         </record>

My odoo version is 9, is that of any reflect?

Thank you and best regards

**Comment by pedrobaeza** [comment]
They are not installable because they are not migrated to odoo 9. Just like that. Please follow the migration progress in https://github.com/OCA/vertical-medical/issues/50

**Comment by xiasun** [comment]
Okay thank you!

2016-02-24 16:28 GMT+08:00 Pedro M. Baeza notifications@github.com:

**Comment by xiasun** [comment]
By the way, is vertical-medical 9.0 fully usable under odoo 8? Strangely, I can only make "medical" and "medical_disease" installable, I cannot install the rest apps/modules even if I have make the flag installable true.

**Comment by pedrobaeza** [comment]
Why are you trying to do such thing? Use the 8.0 branch on version 8.0.

**Comment by juhenriquez** [comment]
For some odd reason I get the same thing for odoo 8, any ideas?

<img width="960" alt="2016-06-11 18_23_26-start" src="https://cloud.githubusercontent.com/assets/8250019/15987734/c0faebb2-3001-11e6-9792-8fe7cae238fc.png">
